- flake.nix
Because the repo follows itself, you get infinite recursion when updating your flake or when checking it, so you get alejandra following alejandra following alejandra, etc. This massively bloats flake.lock sizes and is just not fun to deal with.
Example:
> Remove infinite recursion

- src/rules/key_value.rs
- src/rules/with.rs
- tests/cases/idioms/in
- tests/cases/idioms/out
- tests/cases/with/in
- tests/cases/with/out
Reduces Nixpkgs diff by 10%.
With this and a few pending PRs:
24157 files changed, 1562119 insertions(+), 974518 deletions(-)
> with: attempt to simplify

- src/rules/key_value.rs
- We dont care too much for the with after the apply after a key-value,
and at the same time adding the exception can have weird
interactions when that happens, so the less we have, the better
- 0 bytes of diff in real life:
> feat: remove unnecesary exception

- buildkite.yaml
- src/rules/key_value.rs
- src/rules/with.rs
- tests/cases/with/in
- tests/cases/with/out
- There were some interactions where the user would feel
that indentation levels were missing/excessive
```diff
--- a/doc/doc-support/lib-function-docs.nix
+++ b/doc/doc-support/lib-function-docs.nix
@@ -4,7 +4,8 @@
{ pkgs ? import ./.. { }
, locationsXml
}:
-with pkgs; stdenv.mkDerivation {
+with pkgs;
+stdenv.mkDerivation {
name = "nixpkgs-lib-docs";
src = ./../../lib;
diff --git a/lib/generators.nix b/lib/generators.nix
index 1ec97a7f4..9cec83984 100644
--- a/lib/generators.nix
+++ b/lib/generators.nix
@@ -381,21 +381,23 @@ in
{ }:
v: let
isFloat = builtins.isFloat or (x: false);
-          expr = ind: x: with builtins; if x == null
-          then ""
-          else if isBool x
-          then bool ind x
-          else if isInt x
-          then int ind x
-          else if isString …
```
> feat: improve with

- src/children.rs
- src/config.rs
- src/position.rs
- tests/cases/root/out
```diff
diff --git a/lib/debug.nix b/lib/debug.nix
index cdec524c6..026cf99ef 100644
--- a/lib/debug.nix
+++ b/lib/debug.nix
@@ -1,17 +1,17 @@
/*
Collection of functions useful for debugging
-  broken nix expressions.
+ broken nix expressions.
-  * `trace`-like functions take two values, print
-    the first to stderr and return the second.
-  * `traceVal`-like functions take one argument
-    which both printed and returned.
-  * `traceSeq`-like functions fully evaluate their
-    traced value before printing (not just to â€œweak
-    head normal formâ€ like trace does by default).
-  * Functions that end in `-Fn` take an additional
-    function as their first argument, which is applied
-    to the traced value before it is printed.
+ * `trace`-like functions take two values, print
+ …
```
> fix: position update

- src/rules/string.rs
- tests/cases/string/in
- tests/cases/string/out
```diff
diff --git a/nixos/doc/manual/default.nix b/nixos/doc/manual/default.nix
index 83abb46d0..82b6e89fc 100644
--- a/nixos/doc/manual/default.nix
+++ b/nixos/doc/manual/default.nix
@@ -36,14 +36,14 @@ with pkgs; let
modulesDoc = builtins.toFile "modules.xml" ''
<section xmlns:xi="http://www.w3.org/2001/XInclude" id="modules">
${
-    (
-      lib.concatMapStrings (
-        path: ''
-          <xi:include href="${path}" />
-        ''
-      ) (lib.catAttrs "value" config.meta.doc)
-    )
-  }
+      (
+        lib.concatMapStrings (
+          path: ''
+            <xi:include href="${path}" />
+          ''
+        ) (lib.catAttrs "value" config.meta.doc)
+      )
+    }
</section>
'';
diff --git a/nixos/lib/make-disk-image.nix b/nixos/lib/make-disk-image.nix
index …
```
> feat: nicer string interpolation

- .gitattributes
This is totally another nitpick, but it bothered me that Github lists this repository as almost entirely being Javascript :)
Before this commit:
After this commit:
> Ignore the generated list of nixpkgs files for language stats

- README.md
- flake.nix
- integrations/vscode/yarn.lock.nix
- Users downloading the pre-built binaries are
not copying the closure for gnu/gcc, so
only the static binary would work
> feat: only cross compile static binaries

- src/format.rs
- src/main.rs
Don't print so much when nothing changes. Print some stats at the end. Perhaps should also print any potential errors.
Fixes #139
> Print stats when formatting trees

- Cargo.toml
- README.md
- This cuts the binary size by 40%, and makes runtime 2 seconds faster
> perf: enable lto

- src/alejandra_engine/src/rules/if_else.rs
- src/alejandra_engine/tests/cases/if_else/in
- src/alejandra_engine/tests/cases/if_else/out
```diff
diff --git a/lib/attrsets.nix b/lib/attrsets.nix
index 5d3d7b464..909dc25f7 100644
--- a/lib/attrsets.nix
+++ b/lib/attrsets.nix
@@ -156,14 +156,13 @@ in rec {
v = set.${name};
in
if pred name v
-          then
-            [
-              (nameValuePair name (
-                if isAttrs v
-                then filterAttrsRecursive pred v
-                else v
-              ))
-            ]
+          then [
+            (nameValuePair name (
+              if isAttrs v
+              then filterAttrsRecursive pred v
+              else v
+            ))
+          ]
else []
) (attrNames set)
);
diff --git a/lib/customisation.nix b/lib/customisation.nix
index 9c82f04ba..abd8b0a36 100644
--- a/lib/customisation.nix
+++ b/lib/customisation.nix
@@ -38,11 +38,10 @@
}
// …
```
> feat: less indented if-then-else

- README.md
- installers/aarch64-linux.sh
- installers/x86_64-linux.sh
- I was running Alejandra on my android mobile phone,
and the installers were not helpful, so lets
just stick to the basics
> docs: simplify installation

- flake.nix
(This is completely untested at the moment but I felt it's probably easy to quickly guess what the fix is rather than open issue. Please check before merging!)
Many people are currently using `defaultSystems` (or `flake-utils.lib.eachDefaultSystem` as suggested in the nixos wiki) which [includes i686-linux](https://github.com/numtide/flake-utils/blob/3cecb5b042f7f209c56ffd8371b2711a290ec797/default.nix#L3-L9).
> Supply an i686-linux package

- .pre-commit-entry.sh
- .pre-commit-hooks.yaml
Following #275, this add a [`pre-commit`](https://pre-commit.com) hook so that Alejandra can be added to any project as a pre-commit hook in `.pre-commit-hooks.yaml`. Unlike my previous PR, this does not require altering the repository structure.
The hook does not require Cargo to be installed, Alejandra will be installed and ran via `nix run github:kamadorueda/alejandra`.
The hook can be tested with:
```shell
pre-commit try-repo ./ --verbose
```
> feat: add pre-commit hook (without altering repo structure)

- .pre-commit-hooks.yaml
After seeing the [StyLua's `pre-commit-hooks.yaml`](https://github.com/JohnnyMorganz/StyLua/blob/27c97ca60f580da23af2b06a63231e0373917a64/.pre-commit-hooks.yaml) I realised we could add a `alejandra-system` hook for users who might prefer using their system `alejandra` executable.
The following configuration
```yaml
- repo: https://github.com/kamadorueda/alejandra
rev: main
hooks:
- id: alejandra-system
```
will now call the system binary while 
```yaml
- repo: https://github.com/kamadorueda/alejandra
rev: main
hooks:
- id: alejandra
```
still use the Nix build wrapper script.
> feat: add system pre-commit hook

- README.md
I just discovered [pre-commit-hooks.nix](https://github.com/cachix/pre-commit-hooks.nix) which already supports Alejandra. I thought it was worth mentioning in the documentation.
> docs: add pre-commit-hooks.nix example

- src/alejandra_cli/src/cli.rs
- It was previously inheriting the name of the binary
> fix: name in the cli

- .pre-commit-entry.sh
`!command` is a syntax error, so this check will always "pass", even if `nix-instantiate` doesn't exist.
> fix: Avoid syntax error

- .pre-commit-entry.sh
Someone changed `default.nix` without updating the `pre-commit` hook. See https://github.com/kamadorueda/alejandra/issues/354 for more details.
> Fix https://github.com/kamadorueda/alejandra/issues/354

- .gitignore
- .pre-commit-hooks.yaml
- CHANGELOG.md
- integrations/pre-commit/README.md
@kamadorueda Are you OK with the new no-prerequisites hook replacing the hook which requires Nix? Otherwise I could just rename it.
Closes #370.
> feat: pre-commit hook with no prerequisites

- src/alejandra/src/rules/inherit.rs
- src/alejandra/tests/cases/inherit/out
- src/alejandra/tests/cases/inherit_blank_trailing/in
- src/alejandra/tests/cases/inherit_blank_trailing/out
- src/alejandra/tests/cases/inherit_comment/in
- src/alejandra/tests/cases/inherit_comment/out
Fixes #376
Note that handling of extra newlines in `inherit` statements is still a little janky; usually blank lines will be removed from formatted output, but in some cases (e.g. between an end-of-line comment and a full-line comment) they will be preserved. See the tests added for a few examples of this.
It's probably a good idea to take a position on this (I lean towards collapsing multiple consecutive blank lines into one blank line, but otherwise not removing them from the output) and add it to `STYLE.md` at some point, but that's out-of-scope for this PR. (I didn't want to change the way we format the existing test-cases except to remove trailing whitespace.)
> Don't add blank lines after comments in `inherit`

- integrations/doom-emacs/README.md
Ensure that it plays well with the nix modules installed already. Additionally, the syntax for shell commands with arguments has changed slightly.
> Update instructions for Doom Emacs

- Cargo.lock
- src/alejandra_cli/Cargo.toml
- src/alejandra_cli/src/cli.rs
- src/alejandra_cli/tests/cli.rs
Done by introducing a ALEJANDRA_THREAD env variable instead of adding e.g. `--threads 4` to all existing test cases and update the entire output.txt file (it shows the cli args used). That was the lowest number of lines to change. The cli now uses the `--threads` value, then env var, then falls back to number of physical CPUs. Any better idea?
Also pretty print the assert_eq call of the big output.txt comparison to be actually able to see where things fail with diff. This allowed me to better detect what the PR is fixing by showing e.g.:
```
<  Checking style in 1 file using 4 threads.
>  Checking style in 1 file using 2 threads.
```
> Make tests green on systems with different number of physical CPUs
