- flake.lock
- flake.nix
> fix: devshell cargo version

- .envrc
- .gitignore
- Loads the devshell more conveniently
> chore: add support for .direnv

- README.md
- flake.lock
- flake.nix
- treefmt.toml
- chore: add treefmt - to format them all
- style: treefmt all the things
- style: treefmt w/ rustfmt, as well
- chore: cleaner rustfmt args
> chore: treefmt

- .editorconfig
- README.md
- flake.lock
- flake.nix
- pre-commit.sh
- project a pre-commit hook for contributors
- add an editorconfig
Also add the shortest possible contributing section to the readme
> chore: add a more ergonomic (and cleaner) devshell

- flake.nix
- pre-commit.sh
- these where under the devshell commands section and fell through
> fixup: re-add cargo & treefmt

- flake.nix
- src/rules/lambda.rs
- tests/cases/lambda/out
> lambda: keep on same line

- buildkite.yaml
- it requires to know the branch name
> fix: coverage build

- buildkite.yaml
- flake.nix
> static builds for x86_64-unknown-linux-musl

- buildkite.yaml
- By using two agents and two queues I can
separate the public instance from the one with
secrets
> feat: isolate queues

- front/deploy
- This way it works from a clean checkout
> fix: missing deploy step

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- front/Cargo.lock
- src/cli.rs
- src/lib.rs
- src/main.rs
- src/version.rs
- treefmt.toml
[![asciicast](https://asciinema.org/a/470438.svg)](https://asciinema.org/a/470438)
> feat: add a text user interface

- src/alejandra_engine/src/children.rs
- src/alejandra_engine/src/parsers/pattern.rs
- src/alejandra_engine/src/rules/apply.rs
- src/alejandra_engine/src/rules/assert_and_with.rs
- src/alejandra_engine/src/rules/attr_set.rs
- src/alejandra_engine/src/rules/bin_op_and_or_default.rs
- src/alejandra_engine/src/rules/dynamic.rs
- src/alejandra_engine/src/rules/inherit.rs
- src/alejandra_engine/src/rules/key_value.rs
- src/alejandra_engine/src/rules/lambda.rs
- src/alejandra_engine/src/rules/let_in.rs
- src/alejandra_engine/src/rules/list.rs
- src/alejandra_engine/src/rules/paren.rs
- src/alejandra_engine/src/rules/pat_bind.rs
- src/alejandra_engine/src/rules/pat_entry.rs
- src/alejandra_engine/src/rules/root.rs
- src/alejandra_engine/src/rules/string_interpol.rs
- So they match the meaning more closely
> refactor: rename functions

- src/alejandra_engine/tests/cases/or_default/in
- src/alejandra_engine/tests/cases/or_default/out
- Coverage was 100% before, and it's 100% now as well
- But it's nice to have appropriate tests
> test: make input be or default

- CHANGELOG.md
- Cargo.lock
- src/alejandra_engine/Cargo.toml
- src/alejandra_engine/src/lib.rs
> perf: use mimalloc

- src/alejandra_engine/Cargo.toml
- src/alejandra_engine/src/children.rs
- Nixpkgs in 4 seconds :sunglasses:
> perf: lazy position

- CHANGELOG.md
- README.md
- src/alejandra_cli/src/cli.rs
- Makes my life simpler when benchmarking
> feat: --threads flag

- src/alejandra_cli/src/cli.rs
- src/alejandra_engine/src/format.rs
- Also took the time to improve the messages
so that it is more clear what is being done
> feat: --check no longer modifies files in-place

- src/alejandra_cli/src/cli.rs
- They are now in the repo readme
> refactor: rm authors from help

- Cargo.lock
- src/alejandra_cli/Cargo.toml
- src/alejandra_cli/src/cli.rs
- src/alejandra_cli/src/find.rs
Replace use of clap builder with clap's `#[derive(Parser()]`
> Use clap-derive

- src/alejandra_cli/src/cli.rs
- src/alejandra_cli/src/find.rs
Based on:
https://github.com/kamadorueda/alejandra/pull/274
> feat: respect - for stdin

- README.md
> docs: link style guide in the readme

- README.md
> docs: update timings after last perf improvement

- README.md
> refactor: remove old asciinema

- integrations/neovim/README.md
Merged in https://github.com/dense-analysis/ale/pull/4435#event-8455317286
> Add ALE to list of neovim plugins

- Cargo.lock
- src/alejandra/Cargo.toml
- src/alejandra/tests/fmt.rs
> Make test failures more informative

- flake.nix
Fixes warning raised as a result of https://github.com/NixOS/nixpkgs/pull/246386.
> flake: add meta.mainProgram

- src/alejandra/src/builder.rs
- src/alejandra/src/format.rs
Fixes https://github.com/kamadorueda/alejandra/issues/452
> perf: control recursion depth

- README.md
I admit this is a bit unorthodox and I have full understanding if you want to reject this PR. I actually found myself in the situation where I wanted to format my nix files (in combination with your VSCode extension) on a machine with no Nix installed.
> docs: add homebrew installation method
